### ISSUE TITLE
change default TITANIUM_SDK_VERSION value

### ISSUE THREAD

**Issue by caufang** [PSPDFKit/PSPDFKit-Titanium#4]
Now that 3.5.0.GA is out, should probably change the value inside the titanium.xcconfig file to match.

Also, I would suggest mentioning in the README for users to check these values if they are having problems. I spent several hours trying to debug why the build was failing and only decided to check there based on someone having the same/similar problem in a different titanium-related project: https://github.com/dbubs/myMedia-Titanium-Module/issues/1

**Comment by steipete** [comment]
Thanks! We're currently in the final week of releasing PSPDFKit 4.2 and will then update all of our 3rd-party-extensions (Xamarin, Titanium, Cordova) as well.
