### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by ja8657** [PSPDFKit/PSPDFKit-Titanium#5]
Hello,

I followed instructions on your readme file. I ran ./build.py and the following errors appear:

Traceback (most recent call last):
  File "./build.py", line 219, in <module>
    build_module(manifest,config)
  File "./build.py", line 162, in build_module
    from tools import ensure_dev_path
ImportError: No module named tools

Is there a fix to this? Thank you. Have a nice day

ps. I'm no Python developer so I am not familiar with the source code :)

**Comment by steipete** [comment]
Hi! Over at support.pspdfkit.com we can help you out faster. Have you checked out the submodule and installed Titanium?

**Comment by ja8657** [comment]
Thank you for your quick response. 

I have Titanium 3.4.1 installed but I'm not sure what the submodule is. I just git clone'd based on the instructions. I'm sorry if I missed out on that, but where could you find that submodule?

**Comment by steipete** [comment]
git submodule init
git submodule update

**Comment by ja8657** [comment]
Thank you. Ran those 2 commands, still the same errors :(

**Comment by steipete** [comment]
Please send us an email via support.pspdfkit.com and we'll send you a pre-build binary.
