### ISSUE TITLE
Hi! Is a Titanium Android wrapper in the works?

### ISSUE THREAD

**Issue by markive** [PSPDFKit/PSPDFKit-Titanium#9]

**Comment by steipete** [comment]
Hi! We already have one, it's just not yet public. Ping us on support.pspdfkit.com and I'll send you a binary build. (Android v2 bindings will take another week though)

**Comment by markive** [comment]
Hi steipete, is there an updated Android wrapper for Appcelerator available? Thx

**Comment by rossmacfarlane** [comment]
I am interested in this as well however Appcelerator doesn't support AAR libraries when building the module which is what I believe it stopping the android version for us. I contacted AppC and they said it will be released in the next version at the end of March. So hopefully we see android support soon after!

https://jira.appcelerator.org/browse/TIMOB-18565

**Comment by steipete** [comment]
Yes, we're working with Appcelerator on making this possible. Should be a matter of weeks for a beta now.

**Comment by rossmacfarlane** [comment]
@steipete Thank you!
